------------------------------------------------------------De1-----------------------------------------------------------------------------------------
/*
USE master
GO
DROP DATABASE BAITHI1
*/
--. Tạo database tên BAITHI gồm có 6 table CSCHANNUOI, GIONGVN, 
--DIEUKIENCN, GPCN, CTGP, DOTCN. Tạo khóa chính, khóa ngoại cho các table đó (1.5đ).
USE master
CREATE DATABASE BAITHI1
GO
USE BAITHI1
GO

CREATE TABLE CSCHANNUOI
(
	MACS VARCHAR(5) CONSTRAINT PK_CSCHANNUOI PRIMARY KEY NOT NULL,
	TENCS NVARCHAR(50),
	LOAICS VARCHAR(50),
	NGDAIDIEN VARCHAR(50),
	NGTL SMALLDATETIME,
	DTHOAI VARCHAR(10),
)

CREATE TABLE GIONGVN
(
	MAGIONG VARCHAR(4) CONSTRAINT PK_GIONGVN PRIMARY KEY NOT NULL,
	TENGIONG VARCHAR(50),
	LOAIVN VARCHAR(20)
)

CREATE TABLE DIEUKIENCN
(
	MADK VARCHAR(5) CONSTRAINT PK_DIEUKIEN PRIMARY KEY NOT NULL,
	MACS VARCHAR(5) 
	CONSTRAINT FK_MACS_DIEUKIEN FOREIGN KEY(MACS) REFERENCES CSCHANNUOI(MACS),
	QUYMO INT,
	KCXLCT INT,
	KCKDC INT
)

CREATE TABLE GPCN
(
	MAGP VARCHAR(5) CONSTRAINT PK_GPCN PRIMARY KEY NOT NULL,
	MACS VARCHAR(5),
	NGCAP SMALLDATETIME,
	SOGP VARCHAR(100),
	SOGIONG INT,
	CONSTRAINT FK_MACS_GPCN FOREIGN KEY(MACS) REFERENCES CSCHANNUOI(MACS), 
)

CREATE TABLE CTGP
(
	MAGP VARCHAR(5) NOT NULL,
	MAGIONG VARCHAR(4) NOT NULL,
	SL INT,
	CONSTRAINT PK_CTGP PRIMARY KEY(MAGP, MAGIONG),
	CONSTRAINT FK_MAGP_CTGP FOREIGN KEY(MAGP) REFERENCES GPCN(MAGP),
	CONSTRAINT FK_MAGIONG_CTGP FOREIGN KEY(MAGIONG) REFERENCES GIONGVN(MAGIONG)
)

CREATE TABLE DOTCN
(
	MADOTCN VARCHAR(4) CONSTRAINT PK_DOTCN PRIMARY KEY NOT NULL,
	MACS VARCHAR(5),
	MAGIONG VARCHAR(4),
	SLVN INT,
	NGBD SMALLDATETIME,
	PHGTHUC VARCHAR(50),
	NGXUATDK SMALLDATETIME
	CONSTRAINT FK_MACS_DOTCN FOREIGN KEY(MACS) REFERENCES CSCHANNUOI(MACS),
	CONSTRAINT FK_MAGIONG_DOTCN FOREIGN KEY(MAGIONG) REFERENCES GIONGVN(MAGIONG)
)

--2. Nhập dữ liệu cho 4 bảng CSCHANNUOI, GIONGVN, DIEUKIENCN và GPCN như đề bài
SET DATEFORMAT DMY

INSERT INTO CSCHANNUOI(MACS, TENCS, LOAICS, NGDAIDIEN, NGTL, DTHOAI) VALUES
('CS001','Hoang Mai','Nong ho','Nguyen Thanh Son','19/10/2019','0971507394'),
('CS002','Cong ty TNHH Phung Dầu Sơn','Trang trai quy mo vua','Pham The Hung','20/10/2009','0364266792'),
('CS003','Green Farm','Trang trai quy mo nho','Ho Trung Dai','15/09/2018','0356266782')

INSERT INTO GIONGVN(MAGIONG, TENGIONG, LOAIVN) VALUES
('G001','Bo vang Viet Nam','Bo'),
('G002','Bo Bay Nui','Bo'),
('G003','De nui Ninh Binh','De')

INSERT INTO DIEUKIENCN(MADK, MACS, QUYMO, KCXLCT, KCKDC) VALUES
('DK001','CS001','10','250','300'),
('DK002','CS001','10','200','350'),
('DK003','CS003','30','350','400')

INSERT INTO GPCN(MAGP, MACS, NGCAP, SOGP, SOGIONG) VALUES
('GP001','CS001','10/10/2020','42/001/2020/DKCN','1'),
('GP002','CS001','08/09/2020','43/001/2020/DKCN','2'),
('GP003','CS002','04/06/2010','2/002/2010/DKCN','4')

INSERT INTO CTGP(MAGP, MAGIONG, SL) VALUES
('GP001','G001','10'),
('GP002','G002','10'),
('GP003','G003','10')

INSERT INTO DOTCN(MADOTCN, MACS, MAGIONG, SLVN, NGBD, PHGTHUC, NGXUATDK) VALUES
('D001','CS001','G001','5','15/06/2021','Tha tu do','15/05/2023'),
('D002','CS001','G002','5','15/07/2021','Tha tu do','10/05/2023'),
('D003','CS003','G001','25','20/09/2021','Tha tu do','10/03/2022')

--3. Hiện thực ràng buộc toàn vẹn sau: số lượng vật nuôi từ 100 trở lên không được 
--phép chăn nuôi theo phương thức “thả tự do”
ALTER TABLE DOTCN
ADD CONSTRAINT CHECK_SLVN_PHGTHUC CHECK (
	NOT (SLVN >= 100 AND PHGTHUC = 'Tha tu do')
)


--4. Hiện thực ràng buộc toàn vẹn sau: các giống của loại vật nuôi "Bo" có thời gian 
--xuất dự kiến cách ngày bắt đầu nuôi ít nhất 12 tháng (1.5đ). 
GO
CREATE TRIGGER CHECK_BO_12_THANG ON DOTCN
AFTER INSERT
AS
BEGIN
	IF EXISTS(
		SELECT *
		FROM inserted I, GIONGVN G
		WHERE I.MAGIONG = G.MAGIONG
		AND G.LOAIVN = 'Bo'
		AND DATEDIFF(MONTH, I.NGBD, I.NGXUATDK) < 12
	)
	BEGIN
		RAISERROR('LOI: BO VA TREN 12 THANG', 16, 1)
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT 'THEM THANH CONG!'
	END
END
GO

--5. Tìm các giống vật nuôi (MAGIONG, TENGIONG) thuộc loại “Bo” được chăn nuôi theo phương thức “thả tự do” dự kiến xuất trong tháng 12/2024 (1đ). 
SELECT G.MAGIONG, TENGIONG
FROM GIONGVN G, DOTCN D
WHERE G.MAGIONG = D.MAGIONG AND G.LOAIVN = 'Bo' AND D.PHGTHUC = 'Tha tu do'
AND MONTH(D.NGXUATDK) = 12 AND YEAR(D.NGXUATDK) = 2024

--6. Tìm cơ sở chăn nuôi (MACS, TENCS) chưa có giấy phép chăn nuôi nào được cấp cho giống vật nuôi thuộc loại “De” nhưng đã từng có đợt chăn nuôi các giống vật nuôi loại này trong năm 2024 (1đ). 
SELECT C.MACS, C.TENCS
FROM CSCHANNUOI C
JOIN DOTCN D ON D.MACS = C.MACS
JOIN GIONGVN G ON G.MAGIONG = D.MAGIONG
WHERE LOAIVN = 'De' AND YEAR(NGBD) =2024
	EXCEPT
SELECT C.MACS, C.TENCS
FROM CSCHANNUOI C, GPCN GP, GIONGVN G, CTGP
WHERE C.MACS = GP.MACS AND CTGP.MAGIONG = G.MAGIONG AND CTGP.MAGP = GP.MAGP
AND LOAIVN = 'De'

--7. Tính thời gian nuôi thực tế trung bình (theo đơn vị tháng) của từng loại vật nuôi theo từng hình thức chăn nuôi (1đ). 
-- CACH 1
SELECT G.LOAIVN, D.PHGTHUC, AVG(12*(YEAR(NGXUATDK) - YEAR(NGBD)) + (MONTH(NGXUATDK) - MONTH(NGBD))) THOIGIANNUOITRUNGBINH
FROM DOTCN D, GIONGVN G
WHERE D.MAGIONG = G.MAGIONG
GROUP BY G.LOAIVN, D.PHGTHUC
-- CACH 2
SELECT G.LOAIVN, D.PHGTHUC, AVG(DATEDIFF(MONTH, NGBD, NGXUATDK)) THOIGIANNUOITRUNGBINH
FROM DOTCN D, GIONGVN G
WHERE D.MAGIONG = G.MAGIONG
GROUP BY G.LOAIVN, D.PHGTHUC


--8. Với từng loại vật nuôi tìm giống vật nuôi(MAGIONG) từng được cấp phép với tổng số lượng nhiều nhất năm 2024 (1đ). 
SELECT TOP 1 WITH TIES G.LOAIVN, G.MAGIONG, SUM(D.SLVN) SLVN
FROM GIONGVN G, DOTCN D
WHERE G.MAGIONG = D.MAGIONG AND YEAR(D.NGBD) = 2024
GROUP BY G.LOAIVN, G.MAGIONG
ORDER BY SUM(D.SLVN) DESC

--9. Tìm cơ sở chăn nuôi (MACS, TENCS) đã được cấp phép chăn nuôi tất cả các giống của loại vật nuôi “Bo” với số lượng mỗi giống đều từ 20 trở lên (1đ). 
SELECT C.MACS, C.TENCS
FROM CSCHANNUOI C
WHERE NOT EXISTS(
	SELECT *
	FROM GIONGVN G
	WHERE G.LOAIVN = 'Bo' 
	AND NOT EXISTS (
		SELECT *
		FROM GPCN G1, CTGP CT
		WHERE C.MACS = G1.MACS AND CT.MAGP = G1.MAGP AND CT.MAGIONG = G.MAGIONG
		AND SL >= 20
	)
)

------------------------------------------------------------De2-----------------------------------------------------------------------------------------
--1.	Tạo database tên BAITHI gồm có 6 table CSCHANNUOI, GIONGVN, DIEUKIENCN, GPCN, CTGP, DOTCN. Tạo khóa chính, khóa ngoại cho các table đó (1.5đ). 

/*
USE master
GO
DROP DATABASE BAITHI2
*/
USE master
CREATE DATABASE BAITHI2
GO
USE BAITHI2

CREATE TABLE CSCHANNUOI(
	MACS VARCHAR(5) CONSTRAINT PK_CSCHANNUOI PRIMARY KEY NOT NULL,
	TENCS VARCHAR(20),
	LOAICS VARCHAR(50),
	NGDAIDIEN VARCHAR(50),
	NGTL SMALLDATETIME,
	DTHOAI VARCHAR(10)
)

CREATE TABLE GIONGVN(
	MAGIONG VARCHAR(4) CONSTRAINT PK_GIONGVN PRIMARY KEY NOT NULL,
	TENGIONG VARCHAR(20),
	LOAIVN VARCHAR(20)
)

CREATE TABLE DIEUKIENCN(
	MADK VARCHAR(5) CONSTRAINT PK_DIEUKIENCN PRIMARY KEY NOT NULL,
	MACS VARCHAR(5),
	QUYMO INT,
	KCXLCT  INT,
	KCHTNSH INT,
	CONSTRAINT FK_MACS_DIEUKIENCN FOREIGN KEY(MACS) REFERENCES CSCHANNUOI(MACS)
)

CREATE TABLE GPCN(
	MAGP VARCHAR(5) CONSTRAINT PK_GPCN PRIMARY KEY NOT NULL,
	MACS VARCHAR(5),
	NGCAP SMALLDATETIME,
	SOGP VARCHAR(50),
	SOGIONG INT,
	CONSTRAINT FK_MACS_GPCN FOREIGN KEY(MACS) REFERENCES CSCHANNUOI(MACS)
)

CREATE TABLE CTGP(
	MAGP VARCHAR(5) NOT NULL,
	MAGIONG VARCHAR(4) NOT NULL,
	SL INT,
	CONSTRAINT PK_MAGP_MAGIONG_CTGP PRIMARY KEY(MAGP, MAGIONG),
	CONSTRAINT FK_MAGP_CTGP FOREIGN KEY(MAGP) REFERENCES GPCN(MAGP),
	CONSTRAINT FK_MAGIONG_CTGP FOREIGN KEY(MAGIONG) REFERENCES GIONGVN(MAGIONG)
)

CREATE TABLE DOTCN(
	MADOTCN VARCHAR(4) CONSTRAINT PK_DOTCN PRIMARY KEY NOT NULL,
	MACS VARCHAR(5),
	MAGIONG VARCHAR(4),
	SLVN INT,
	NGBD SMALLDATETIME,
	PHGTHUC VARCHAR(20),
	NGXUATDK SMALLDATETIME,
	CONSTRAINT FK_MACS_DOTCN FOREIGN KEY(MACS) REFERENCES CSCHANNUOI(MACS),
	CONSTRAINT FK_MAGIONG_DOTCN FOREIGN KEY(MAGIONG) REFERENCES GIONGVN(MAGIONG)
)
--2.	Nhập dữ liệu cho 4 bảng CSCHANNUOI, GIONGVN, DIEUKIENCN và GPCN như đề bài (1đ). 
SET DATEFORMAT DMY

INSERT INTO CSCHANNUOI(MACS , TENCS , LOAICS , NGDAIDIEN , NGTL , DTHOAI ) VALUES
('CS001 ','Tam Viet ','Nong ho ','Bui Phu Lam ','19/10/2018 ','0971507142 '),
('CS002 ','Cam My ','Trang trai quy mo vua ','Le Thi Hong Tuyet ','20/10/2008 ','0364266762 '),
('CS003 ','Me Non ','Trang trai quy mo nho ','Ngo Van Thanh ','15/09/2017 ','0356266967 ')

INSERT INTO GIONGVN(MAGIONG , TENGIONG , LOAIVN ) VALUES
('G001 ','Heo ba xuyen ','Heo '),
('G002 ','Heo moi ','Heo '),
('G003 ','Bo lai Sind ','Bo ')

INSERT INTO GPCN(MAGP, MACS, NGCAP, SOGP, SOGIONG) VALUES
('GP001 ','CS001 ','10/10/2019 ','42/001/2019/DKCN ','1 '),
('GP002 ','CS001 ','08/09/2019 ','43/001/2019/DKCN ','2 '),
('GP003 ','CS002 ','04/06/2009 ','2/002/2009/DKCN ','4 ')

INSERT INTO CTGP(MAGP , MAGIONG , SL ) VALUES
('GP001 ','G001 ','10 '),
('GP002 ','G002 ','10 '),
('GP002 ','G003 ','10 ')

INSERT INTO DOTCN(MADOTCN , MACS , MAGIONG , SLVN , NGBD , PHGTHUC , NGXUATDK ) VALUES
('D001 ','CS001 ','G001 ','5 ','15/06/2021 ','Nuoi cong nghiep ','15/09/2021 '),
('D002 ','CS001 ','G002 ','5 ','15/07/2021 ','Tha tu do ','10/01/2022 '),
('D003 ','CS003 ','G001 ','25 ','20/09/2021 ','Tha tu do ','10/08/2023 ')

--3.Hiện thực ràng buộc toàn vẹn sau: các giấy phép được cấp trước năm 2019 có số giống được cấp phép tối đa 5 giống một lần cấp (1đ). 
/*ALTER TABLE GPCN
ADD CONSTRAINT CHK_CAPPHEP CHECK(YEAR(NGCAP) < 2019 AND SOGIONG <= 5)
-- KHONG THE CONSTRAINT DUOC VI CHECK KHONG HO TRO HAM YEAR*/
GO
CREATE TRIGGER TRG_CAPPHEP ON GPCN
AFTER INSERT
AS
BEGIN
	IF EXISTS(
		SELECT *
		FROM inserted I
		WHERE YEAR(I.NGCAP) >= 2019 OR I.SOGIONG > 5
	)
	BEGIN
		RAISERROR('LOI: KHONG THOA NAM < 2019 VA SOGIONG')
		ROLLBACK TRAN
	END
	ELSE
	BEGIN
		PRINT 'THEM THANH CONG!' 
	END
END

--4.Hiện thực ràng buộc toàn vẹn sau: các giống vật nuôi loại "Heo" chỉ được cấp giấy phép chăn nuôi với số lượng tối đa là 100 vật nuôi (1.5đ). 
GO
CREATE TRIGGER TRG_CHECK_SOLUONG_HEO ON GIONGVN
AFTER INSERT
AS
BEGIN
	IF EXISTS(
		SELECT *
		FROM inserted I, CTGP C
		WHERE I.MAGIONG = C.MAGIONG AND LOAIVN = 'Heo' AND SL > 100
	)
	BEGIN
		RAISERROR('LOI: SO LUONG HEO IT HON 100', 16, 1)
		ROLLBACK TRAN
	END
	ELSE
	BEGIN
		PRINT 'THEM THANH CONG!'
	END
END

--5.Tìm các cơ sở chăn nuôi (MACS, TENCS) thuộc loại “nong ho” có quy mô trên 30 vật nuôi và có khoảng cách đến khu xử lý chất thải dưới 200 mét (1đ). 
SELECT C.MACS, C.TENCS
FROM CSCHANNUOI C, DIEUKIENCN D
WHERE C.MACS = D.MACS AND LOAICS = 'Nong ho' AND QUYMO > 30 AND KCXLCT < 200

--6.Tìm các giống vật nuôi (MAGIONG, TENGIONG) thuộc loại “Bo” đã từng được cấp phép chăn nuôi nhưng chưa được nuôi đợt nào năm 2024 (1đ).  
SELECT GV.MAGIONG, GV.TENGIONG
FROM GIONGVN GV, CTGP C
WHERE GV.MAGIONG = C.MAGIONG AND LOAIVN = 'Bo'
	EXCEPT
SELECT GV.MAGIONG, GV.TENGIONG
FROM GIONGVN GV, DOTCN D
WHERE GV.MAGIONG = D.MAGIONG AND LOAIVN = 'Bo' AND YEAR(NGBD) = 2024


--7.Tính thời gian nuôi thực tế dài nhất (theo đơn vị tháng) của từng loại vật nuôi theo từng hình thức chăn nuôi (1đ). 
SELECT G.LOAIVN, D.PHGTHUC, MAX(DATEDIFF(MONTH, D.NGBD, D.NGXUATDK)) AS MaxDuration
FROM DOTCN D
JOIN GIONGVN G ON D.MAGIONG = G.MAGIONG
GROUP BY G.LOAIVN, D.PHGTHUC;

--8.	Với từng loại vật nuôi tìm giống vật nuôi (MAGIONG) từng được chăn nuôi với tổng số lượng nuôi thực tế nhiều nhất năm 2024 (1đ). 
SELECT TOP 1 WITH TIES D.MAGIONG, LOAIVN, SUM(SLVN)
FROM DOTCN D, GIONGVN G
WHERE D.MAGIONG = G.MAGIONG AND YEAR(NGBD) = 2024
GROUP BY D.MAGIONG, LOAIVN
ORDER BY SUM(SLVN) DESC

--9.	Tìm cơ sở chăn nuôi (MACS, TENCS) đã từng chăn nuôi tất cả các giống của loại vật nuôi “Heo” với số lượng chăn nuôi thực tế từ 20 vật nuôi trở lên (1đ). 
SELECT C.MACS, C.TENCS
FROM CSCHANNUOI C
WHERE NOT EXISTS (
    SELECT *
    FROM GIONGVN G
    WHERE G.LOAIVN = 'Heo'
    AND NOT EXISTS (
        SELECT *
        FROM DOTCN D
        WHERE D.MACS = C.MACS 
          AND D.MAGIONG = G.MAGIONG
          AND D.SLVN >= 20
    )
)

/*
USE master
GO
DROP DATABASE BAITHI
GO
*/
------------------------------------------------------------De3-----------------------------------------------------------------------------------------
--1.	Tạo database tên BAITHI gồm có 6 table SACH, DVTOCHUC, SUKIEN, NGTHAMGIA, THAMGIA, DANHGIA. Tạo khóa chính, khóa ngoại cho các table đó (1.5đ). 
CREATE DATABASE BAITHI3 
GO
USE BAITHI3
GO

CREATE TABLE SACH (
	MASACH VARCHAR(4) CONSTRAINT PK_SACH PRIMARY KEY NOT NULL, 
	TENSACH VARCHAR(100), 
	THELOAI VARCHAR(50), 
	TACGIA VARCHAR(50), 
	NGXB SMALLDATETIME, 
	NHAXB VARCHAR(100)
) 

CREATE TABLE DVTOCHUC (
	MADV VARCHAR(5) CONSTRAINT PK_DVTOCHUC PRIMARY KEY NOT NULL, 
	TENDV VARCHAR(50), 
	TENNGDD VARCHAR(50), 
	NGTL SMALLDATETIME
)  

CREATE TABLE SUKIEN (
	MASK VARCHAR(5) CONSTRAINT PK_SUKIEN PRIMARY KEY NOT NULL, 
	MASACH VARCHAR(4), 
	MADV VARCHAR(5), 
	TGBD SMALLDATETIME, 
	TGKT SMALLDATETIME, 
	DIADIEM VARCHAR(100),  
	SLDK INT,
	CONSTRAINT FK_MASACH_SUKIEN FOREIGN KEY(MASACH) REFERENCES SACH(MASACH),
	CONSTRAINT FK_MADV_SUKIEN FOREIGN KEY(MADV) REFERENCES DVTOCHUC(MADV),
) 

CREATE TABLE NGTHAMGIA (
	MANTG VARCHAR(4) CONSTRAINT PK_NGTHAMGIA PRIMARY KEY NOT NULL,
	TENNTG VARCHAR(50),
	GIOITINH VARCHAR(4),
	NGSINH SMALLDATETIME,
	NGHENGHIEP VARCHAR(20)
)

CREATE TABLE THAMGIA (
	MANTG VARCHAR(4) NOT NULL,
	MASK VARCHAR(5) NOT NULL, 
	VAITRO VARCHAR(50),
	CONSTRAINT PK_THAMGIA PRIMARY KEY (MANTG, MASK),
	CONSTRAINT FK_MANTG_THAMGIA FOREIGN KEY(MANTG) REFERENCES NGTHAMGIA(MANTG),
	CONSTRAINT FK_MASK_SUKIEN FOREIGN KEY(MASK) REFERENCES SUKIEN(MASK),
)  

CREATE TABLE DANHGIA (
	MADG VARCHAR(5) CONSTRAINT PK_DANHGIA PRIMARY KEY NOT NULL,
	MANTG VARCHAR(4),
	MASK VARCHAR(5),
	TGDG SMALLDATETIME,
	DIEMSO INT,
	NHANXET VARCHAR(20),
	CONSTRAINT FK_MANTG_DANHGIA FOREIGN KEY(MANTG) REFERENCES NGTHAMGIA(MANTG),
	CONSTRAINT FK_MASK_DANHGIA FOREIGN KEY(MASK) REFERENCES SUKIEN(MASK),
)  

--2.	Nhập dữ liệu cho 4 bảng SACH, DVTOCHUC, NGTHAMGIA và SUKIEN như đề bài (1đ). 
SET DATEFORMAT DYM
INSERT INTO SACH(MASACH , TENSACH , THELOAI , TACGIA , NGXB , NHAXB ) VALUES 
('S001 ','Tien kiep va luan hoi ','Phat giao ','Brian L. Weiss ','12/06/2012 ','Phuong dong '),
('S002 ','Giao dục Van hoa hien dai cho hoc sinh Trung hoc pho thong ','Giao duc  ','Bui Thanh Huyen ','12/12/2020 ','Dai hoc su pham TP.HCM '),
('S003 ','Gio dong rung ruc ','Truyen ngan ','Hoang Le Thuy ','20/06/2024 ','Tre ')

INSERT INTO DVTOCHUC (MADV, TENDV, TENNGDD, NGTL)  VALUES 
('DV001 ','Net nam ','Nguyen Van Qua ','15/06/2009 '),
('DV002 ','Anh Sao  ','Mai Thu Van ','20/12/2017 '),
('DV003 ','Sai gon Light ','Huynh Van Thanh  ','21/09/2012 ')

INSERT INTO SUKIEN (MASK, MASACH, MADV, TGBD, TGKT, DIADIEM, SLDK)  VALUES 
('SK001 ','S001 ','DV001 ','16/04/2023 09:00:00 ','16/04/2023 11:00:00 ','Dai hoc Bach Khoa TP.HCM ','100 '),
('SK002 ','S001 ','DV001 ','16/05/2023 09:00:00 ','16/05/2023 11:00:00 ','Dai hoc Bach Khoa Ha Noi ','100 '),
('SK003 ','S003 ','DV002 ','17/05/2024 08:30:00 ','17/05/2024 10:00:00 ','Nguyen Van Binh, Ben nghe, Quan 1 ','150 ')

INSERT INTO NGTHAMGIA (MANTG, TENNTG, GIOITINH, NGSINH, NGHENGHIEP)  VALUES 
('N001 ','Huynh Van Nghe ','Nam ','12/05/1994 ','Giao vien '),
('N002 ','Do Trong Hoan ','Nam ','16/07/1999 ','Giang vien '),
('N003 ','Nguyen Van Ba ','Nam ','17/02/2004 ','Sinh vien ')

INSERT INTO THAMGIA (MANTG, MASK, VAITRO)   VALUES 
('N001 ','SK001 ','Khach tham gia '),
('N002 ','SK001 ','Khach moi '),
('N003 ','SK002 ','Khach tham gia ')

INSERT INTO DANHGIA (MADG, MANTG, MASK, TGDG, DIEMSO, NHANXET)   VALUES 
('DG001 ','N001 ','SK001 ','16/04/2023 11:30:00 ','4 ','To chuc tot '),
('DG002 ','N002 ','SK001 ','16/04/2023 11:45:00 ','5 ','Tot '),
('DG003 ','N003 ','SK002 ','16/05/2024 11:30:00 ','3 ','Tam duoc ')

--3.Hiện thực ràng buộc toàn vẹn sau: sách từ các nhà xuất bản là các đại học ở Tp.Hồ Chí Minh (có chứa “Dai hoc” và “TP.HCM” trong tên nhà xuất bản) chỉ có sau năm 2000 (1đ). 
ALTER TABLE SACH DROP CONSTRAINT KIEMTRA_NXB_SAU2000
-- CACH 1
ALTER TABLE SACH
ADD CONSTRAINT KIEMTRA_NXB_SAU2000 CHECK(
	NOT (NHAXB LIKE '%Dai hoc%TP.HCM%' AND YEAR(NGXB) <= 2000)
)
-- CACH 2
GO
CREATE TRIGGER TRG_CHECK_NXB_SAU2000 ON SACH
AFTER INSERT
AS
BEGIN
	IF EXISTS(
		SELECT *
		FROM inserted I
		WHERE I.NHAXB LIKE '%Dai hoc%TP.HCM%' AND YEAR(I.NGXB) <= 2000
	)
	BEGIN
		RAISERROR('LOI: DAI HOC CO TPHCM XET SAU NAM 2000')
		ROLLBACK TRAN
	END
	ELSE
	BEGIN
		PRINT 'THEM THANH CONG!' 
	END
END

--4.Hiện thực ràng buộc toàn vẹn sau: chỉ người có tham gia vào sự kiện và tham gia với vai trò không phải là “host” mới được đánh giá sự kiện (1.5đ). 
GO
CREATE TRIGGER TRG_DANHGIA ON DANHGIA
AFTER INSERT
AS
BEGIN
	IF EXISTS(
		SELECT *
		FROM inserted I, THAMGIA T
		WHERE I.MANTG = T.MANTG AND I.MASK = T.MASK AND VAITRO = 'host'
	)
	BEGIN
		RAISERROR('LOI: NGUOI THAM GIA SU KIEN KHONG PHAI LA HOST', 16, 1)
		ROLLBACK TRAN
	END
	ELSE
	BEGIN
		PRINT 'THEM THANH CONG!'
	END
END	

--5.	Tìm người tham gia (MANTG, TENNTG, NGSINH) đã tham gia các sự kiện ra mắt sách của nhà xuất bản “Tre” trong tháng 02/2023, sắp xếp kết quả trả về theo ngày sinh tăng dần (1đ). 
SELECT N.MANTG, TENNTG, NGSINH
FROM NGTHAMGIA N, SACH S, SUKIEN SK, THAMGIA T
WHERE  S.MASACH = SK.MASK AND N.MANTG = T.MANTG AND SK.MASK = T.MASK
AND YEAR(NGXB) = 2023 AND MONTH(NGXB) = 2 AND S.NHAXB = 'Tre'
ORDER BY NGSINH ASC

--6.	Tìm người tham gia (MANTG, TENNTG) đã tham gia và đưa ra đánh giá về các sự kiện ra mắt sách của nhà xuất bản “Phuong dong”, trong đó không có đánh giá nào có điểm dưới 4 (1đ).  
SELECT N.MANTG, TENNTG
FROM NGTHAMGIA N
JOIN THAMGIA T ON T.MANTG = N.MANTG
JOIN SUKIEN SK ON SK.MASK = T.MASK
JOIN SACH S ON S.MASACH = SK.MASACH
WHERE S.NHAXB = 'Phuong dong'
	EXCEPT
SELECT N.MANTG, TENNTG
FROM NGTHAMGIA N
JOIN THAMGIA T ON T.MANTG = N.MANTG
JOIN SUKIEN SK ON SK.MASK = T.MASK
JOIN SACH S ON S.MASACH = SK.MASACH
JOIN DANHGIA D ON D.MASK = SK.MASK
WHERE DIEMSO < 4
-- CACH 2
SELECT DISTINCT NGTHAMGIA.MANTG, NGTHAMGIA.TENNTG
FROM NGTHAMGIA
JOIN DANHGIA ON NGTHAMGIA.MANTG = DANHGIA.MANTG
JOIN SUKIEN ON DANHGIA.MASK = SUKIEN.MASK
JOIN SACH ON SUKIEN.MASACH = SACH.MASACH
WHERE SACH.NHAXB = 'Phuong dong'
  AND NOT EXISTS (
      SELECT 1
      FROM DANHGIA D
      WHERE D.MANTG = NGTHAMGIA.MANTG
        AND D.MASK = DANHGIA.MASK
        AND D.DIEMSO < 4
  )

-- 7.	Thống kê độ tuổi trung bình của người tham gia theo từng nhóm nghề nghiệp của mỗi sự kiện (1đ). 
SELECT N.TENNTG, N.NGHENGHIEP, AVG(YEAR(GETDATE()) - YEAR(N.NGSINH)) TUOITRUNGBINH
FROM NGTHAMGIA N
JOIN THAMGIA T ON T.MANTG = N.MANTG
JOIN SUKIEN SK ON SK.MASK = T.MASK 
GROUP BY N.TENNTG, N.NGHENGHIEP
GO
-- 2024 = YEAR(GETDATE())
--8.	Tìm sự kiện (MASK, DIADIEM) có số lượng học sinh tham gia nhiều nhất của từng đơn vị tổ chức (1đ). 
-- CACH 1
SELECT SK.MASK, DIADIEM, SK.MADV, COUNT(N.MANTG) SOHOCSINH
FROM SUKIEN SK
JOIN THAMGIA T ON T.MASK = SK.MASK
JOIN NGTHAMGIA N ON N.MANTG = T.MANTG
WHERE N.NGHENGHIEP = 'Hoc sinh'
GROUP BY SK.MASK, DIADIEM, SK.MADV
HAVING COUNT(N.MANTG) >= ALL (
		SELECT COUNT(N.MANTG) SOHOCSINH
		FROM SUKIEN SK
		JOIN THAMGIA T ON T.MASK = SK.MASK
		JOIN NGTHAMGIA N ON N.MANTG = T.MANTG
		WHERE N.NGHENGHIEP = 'Hoc sinh'
		GROUP BY SK.MASK, DIADIEM, SK.MADV
)

-- CACH 2
SELECT MASK, DIADIEM
FROM SUKIEN SK
WHERE MASK = (
	SELECT TOP 1 WITH TIES SK1.MASK
	FROM NGTHAMGIA N
	JOIN THAMGIA T ON T.MANTG = N.MANTG
	JOIN SUKIEN SK1 ON SK1.MASK = T.MASK
	WHERE SK.MASK = SK1.MASK AND N.NGHENGHIEP = 'Hoc sinh'
	GROUP BY SK1.MASK
	ORDER BY COUNT(N.MANTG) DESC
)

--9.	Tìm người tham gia (MANTG, TENNTG) từng tham gia tất cả các sự kiện ra mắt sách của nhà xuất bản “Tre” với vai trò “khach moi” (1đ). 
SELECT MANTG, TENNTG
FROM NGTHAMGIA N
WHERE NOT EXISTS(
	SELECT *
	FROM SUKIEN SK
	JOIN SACH S ON SK.MASACH = S.MASACH 
	WHERE S.NHAXB = 'Tre'
	AND NOT EXISTS(
		SELECT *
		FROM THAMGIA T
		WHERE T.MANTG = N.MANTG AND T.MASK = SK.MASK
		AND VAITRO = 'Khach moi'
	)
)

------------------------------------------------------------De4-----------------------------------------------------------------------------------------
--1.	Tạo database tên BAITHI gồm có 6 table SACH, DVTOCHUC, SUKIEN, NGTHAMGIA, THAMGIA, DANHGIA. Tạo khóa chính, khóa ngoại cho các table đó (1.5đ). 
CREATE DATABASE BAITHI4 
GO
USE BAITHI4
GO

CREATE TABLE SACH (
	MASACH VARCHAR(4) CONSTRAINT PK_SACH PRIMARY KEY NOT NULL, 
	TENSACH VARCHAR(100), 
	THELOAI VARCHAR(50), 
	TACGIA VARCHAR(50), 
	NGXB SMALLDATETIME, 
	NHAXB VARCHAR(100)
) 

CREATE TABLE DVTOCHUC (
	MADV VARCHAR(5) CONSTRAINT PK_DVTOCHUC PRIMARY KEY NOT NULL, 
	TENDV VARCHAR(50), 
	TENNGDD VARCHAR(50), 
	NGTL SMALLDATETIME
)  

CREATE TABLE SUKIEN (
	MASK VARCHAR(5) CONSTRAINT PK_SUKIEN PRIMARY KEY NOT NULL, 
	MASACH VARCHAR(4), 
	MADV VARCHAR(5), 
	TGBD SMALLDATETIME, 
	TGKT SMALLDATETIME, 
	DIADIEM VARCHAR(100),  
	SLDK INT,
	CONSTRAINT FK_MASACH_SUKIEN FOREIGN KEY(MASACH) REFERENCES SACH(MASACH),
	CONSTRAINT FK_MADV_SUKIEN FOREIGN KEY(MADV) REFERENCES DVTOCHUC(MADV),
) 

CREATE TABLE NGTHAMGIA (
	MANTG VARCHAR(4) CONSTRAINT PK_NGTHAMGIA PRIMARY KEY NOT NULL,
	TENNTG VARCHAR(50),
	GIOITINH VARCHAR(4),
	NGSINH SMALLDATETIME,
	NGHENGHIEP VARCHAR(20)
)

CREATE TABLE THAMGIA (
	MANTG VARCHAR(4) NOT NULL,
	MASK VARCHAR(5) NOT NULL, 
	VAITRO VARCHAR(50),
	CONSTRAINT PK_THAMGIA PRIMARY KEY (MANTG, MASK),
	CONSTRAINT FK_MANTG_THAMGIA FOREIGN KEY(MANTG) REFERENCES NGTHAMGIA(MANTG),
	CONSTRAINT FK_MASK_SUKIEN FOREIGN KEY(MASK) REFERENCES SUKIEN(MASK),
)  

CREATE TABLE DANHGIA (
	MADG VARCHAR(5) CONSTRAINT PK_DANHGIA PRIMARY KEY NOT NULL,
	MANTG VARCHAR(4),
	MASK VARCHAR(5),
	TGDG SMALLDATETIME,
	DIEMSO INT,
	NHANXET VARCHAR(20),
	CONSTRAINT FK_MANTG_DANHGIA FOREIGN KEY(MANTG) REFERENCES NGTHAMGIA(MANTG),
	CONSTRAINT FK_MASK_DANHGIA FOREIGN KEY(MASK) REFERENCES SUKIEN(MASK),
)  
--2.	Nhập dữ liệu cho 4 bảng SACH, DVTOCHUC, NGTHAMGIA và SUKIEN như đề bài (1đ). 

INSERT INTO SACH(MASACH , TENSACH , THELOAI , TACGIA , NGXB , NHAXB ) VALUES
('S001 ','Dat Viet yeu men ','Van hoa ','Pham Cong Son ','12/03/2022 ','Phuong dong '),
('S002 ','Ly luan day hoc Ngu Van ','Giao duc ','Lam Tran Son ','06/05/2023 ','Dai hoc Quoc gia TP.HCM '),
('S003 ','Lung nguoi tham tham ','Truyen ngan ','Vu Thi Huyen Trang ','12/03/2024 ','Tre ')

INSERT INTO DVTOCHUC (MADV, TENDV, TENNGDD, NGTL)   VALUES
('DV001 ','RI Event ','Nguyen Cong Ninh ','09/08/2013 '),
('DV002 ','Mediapro ','Huynh Long An ','12/12/2004 '),
('DV003 ','Hoang sa Viet ','Nguyen Ngoc Lan ','16/04/2017 ')

INSERT INTO SUKIEN (MASK, MASACH, MADV, TGBD, TGKT, DIADIEM, SLDK)  VALUES
('SK001 ','S001 ','DV003 ','16/04/2023 09:00:00 ','16/04/2023 11:00:00 ','Dai hoc su pham TP.HCM ','150 '),
('SK002 ','S001 ','DV003 ','16/05/2023 09:00:00 ','16/05/2023 11:00:00 ','Nguyen Van Binh, Ben nghe, Quan 1 ','200 '),
('SK003 ','S002 ','DV001 ','17/05/2024 08:30:00 ','17/05/2024 10:00:00 ','Dai hoc Bach Khoa TP.HCM ','100 ')

INSERT INTO NGTHAMGIA (MANTG, TENNTG, GIOITINH, NGSINH, NGHENGHIEP)  VALUES
('N001 ','Huynh Long Nhat ','Nam ','15/08/1999 ','Giao vien '),
('N002 ','Nguyen Yen Nhi ','Nu ','16/04/2003 ','Sinh vien '),
('N003 ','Mai Thi Yen ','Nu ','17/05/2010 ','Hoc sinh ')

INSERT INTO THAMGIA (MANTG, MASK, VAITRO)   VALUES
('N001 ','SK001 ','Khach tham gia '),
('N002 ','SK001 ','Khach moi '),
('N001 ','SK003 ','Khach tham gia ')

INSERT INTO DANHGIA (MADG, MANTG, MASK, TGDG, DIEMSO, NHANXET)   VALUES
('DG001 ','N001 ','SK001 ','16/04/2023 11:30:00 ','4 ','To chuc tot'),
('DG002 ','N001 ','SK003 ','17/05/2024 11:45:00 ','5 ','Tot'),
('DG003 ','N002 ','SK001 ','16/04/2023 11:15:00 ','3 ','Tam duoc')

--3.	Hiện thực ràng buộc toàn vẹn sau: các sự kiện ra mắt sách được tổ chức ở các trường đại học ở Tp.Hồ Chí Minh (có “Dai hoc” và “TP.HCM” trong địa điểm tổ chức) đều có số lượng dự kiến không vượt quá 300 người (1đ). 
ALTER TABLE SUKIEN DROP CONSTRAINT CHECK_SUKIEN

ALTER TABLE SUKIEN
ADD CONSTRAINT CHECK_SUKIEN CHECK(
	NOT(DIADIEM LIKE 'Dai hoc%TP.HCM' AND SLDK > 300)
)

--4.	Hiện thực ràng buộc toàn vẹn sau: chỉ người có tham gia sự kiện và tham gia với vai trò là “khach tham gia” mới được đánh giá sự kiện (1.5đ). 
GO
CREATE TRIGGER TRG_CHECK_DANHGIA ON DANHGIA
AFTER INSERT
AS
BEGIN
    IF EXISTS (
        SELECT *
        FROM inserted I
        JOIN THAMGIA T ON I.MANTG = T.MANTG AND I.MASK = T.MASK
        WHERE T.VAITRO <> 'khach tham gia'
    )
    BEGIN
        RAISERROR('LOI: KHACH THAM GIA', 16, 1);
        ROLLBACK TRANSACTION;
    END
	ELSE
	BEGIN
		PRINT 'THEM THANH CONG!'
	END
END


--5.	Tìm người tham gia (MANTG, TENNTG, NGSINH) đã tham gia các sự kiện ra mắt sách của tác giả “Pham Cong Son” trong tháng 01/2023, sắp xếp kết quả trả về theo ngày sinh giảm dần (1đ). 
SELECT N.MANTG, TENNTG, NGSINH
FROM NGTHAMGIA N
JOIN THAMGIA T ON T.MANTG = N.MANTG
JOIN SUKIEN SK ON SK.MASK = T.MASK
JOIN SACH S ON S.MASACH = SK.MASACH
WHERE S.TACGIA = 'Pham Cong Son' AND MONTH(NGXB) = 1 AND YEAR(NGXB) = 2023
ORDER BY NGSINH DESC

--6.	Tìm người tham gia (MANTG, TENNTG) đã tham gia và đưa ra đánh giá về các sự kiện ra mắt sách được tổ chức bởi đơn vị “Mediapro”, trong đó không có đánh giá nào có đểm trên 2 (1đ).  
-- CACH 1
SELECT N.MANTG, TENNTG
FROM NGTHAMGIA N
JOIN THAMGIA T ON T.MANTG = N.MANTG
JOIN DANHGIA D ON D.MANTG = N.MANTG
JOIN SUKIEN SK ON SK.MASK = T.MASK
JOIN DVTOCHUC DV ON DV.MADV = SK.MADV
WHERE DV.TENDV = 'Mediapro'
AND NOT EXISTS(
	SELECT N.MANTG, TENNTG
	FROM NGTHAMGIA N
	JOIN THAMGIA T ON T.MANTG = N.MANTG
	JOIN DANHGIA D ON D.MANTG = N.MANTG
	JOIN SUKIEN SK ON SK.MASK = T.MASK
	JOIN DVTOCHUC DV ON DV.MADV = SK.MADV
	WHERE DIEMSO > 2
)
-- CACH 2
SELECT N.MANTG, TENNTG
FROM NGTHAMGIA N
JOIN THAMGIA T ON T.MANTG = N.MANTG
JOIN DANHGIA D ON D.MANTG = N.MANTG
JOIN SUKIEN SK ON SK.MASK = T.MASK
JOIN DVTOCHUC DV ON DV.MADV = SK.MADV
WHERE DV.TENDV = 'Mediapro'
	EXCEPT 
SELECT N.MANTG, TENNTG
FROM NGTHAMGIA N
JOIN THAMGIA T ON T.MANTG = N.MANTG
JOIN DANHGIA D ON D.MANTG = N.MANTG
JOIN SUKIEN SK ON SK.MASK = T.MASK
JOIN DVTOCHUC DV ON DV.MADV = SK.MADV
WHERE DIEMSO > 2

--7.	Thống kê số người tham gia đánh giá với điểm số là 5 (không trùng) theo từng sự kiện của mỗi đơn vị tổ chức (1đ). 
-- CACH 1
SELECT N.TENNTG,DV.TENDV, COUNT(DISTINCT N.MANTG) SONGUOITHAMGIA
FROM NGTHAMGIA N
JOIN THAMGIA T ON T.MANTG = N.MANTG
JOIN SUKIEN SK ON SK.MASK = T.MASK
JOIN DANHGIA D ON D.MANTG = N.MANTG
JOIN DVTOCHUC DV ON DV.MADV = SK.MADV
WHERE DIEMSO = 5
GROUP BY N.TENNTG, N.MANTG, DV.TENDV
-- CACH 2
SELECT N.TENNTG, SK.MASK, DV.TENDV, COUNT(DISTINCT D.MANTG) AS SO_NGUOI_DANHGIA_5
FROM SUKIEN SK
JOIN DVTOCHUC DV ON SK.MADV = DV.MADV
JOIN DANHGIA D ON SK.MASK = D.MASK
JOIN NGTHAMGIA N ON N.MANTG = D.MANTG
WHERE D.DIEMSO = 5
GROUP BY N.TENNTG, SK.MASK, DV.TENDV;

--8.	Tìm sự kiện (MASK, DIADIEM) có số lượt đánh giá với điểm số 5 nhiều nhất của từng đơn vị tổ chức (không xét thời điểm đánh giá) (1đ). 
-- CACH 1
SELECT SK.MASK, DIADIEM, SK.MADV, COUNT(MANTG) SOLUONG
FROM SUKIEN SK
JOIN DANHGIA D ON D.MASK = SK.MASK
WHERE DIEMSO = 5 
GROUP BY SK.MASK, DIADIEM, SK.MADV
HAVING COUNT(MANTG) >= ALL(
	SELECT COUNT(MANTG) SOLUONG
	FROM SUKIEN SK
	JOIN DANHGIA D ON D.MASK = SK.MASK
	WHERE DIEMSO = 5 
	GROUP BY SK.MASK, DIADIEM, SK.MADV
)

-- CACH 2
SELECT TOP 1 WITH TIES SK.MASK, DIADIEM, DV.MADV, COUNT(MANTG) SOLUONG
FROM SUKIEN SK
JOIN DANHGIA D ON D.MASK = SK.MASK 
JOIN DVTOCHUC DV ON DV.MADV = SK.MADV
WHERE DIEMSO = 5
GROUP BY SK.MASK, DIADIEM, DV.MADV
ORDER BY COUNT(D.MADG) DESC

--9.	Tìm người tham gia (MANTG, TENNTG) từng đánh giá tất cả các sự kiện ra mắt sách của tác giả “Lam Tran Son” với điểm số từ 4 trở lên (không xét thời điểm đánh giá) (1đ).
SELECT MANTG, TENNTG
FROM NGTHAMGIA N
WHERE NOT EXISTS(
	SELECT *
	FROM SUKIEN SK
	JOIN SACH S ON SK.MASACH = S.MASACH
	WHERE S.TACGIA = 'Lam Tran Son'
	AND NOT EXISTS(
		SELECT *
		FROM DANHGIA D
		WHERE D.MASK = SK.MASK AND D.MANTG = N.MANTG
		AND DIEMSO > 4
	)
)