------------------------------------------------------------De1-----------------------------------------------------------------------------------------
/*
USE master
GO
DROP DATABASE BAITHI1
*/
--. Tạo database tên BAITHI gồm có 6 table CSCHANNUOI, GIONGVN, 
--DIEUKIENCN, GPCN, CTGP, DOTCN. Tạo khóa chính, khóa ngoại cho các table đó (1.5đ).
USE master
CREATE DATABASE BAITHI1
GO
USE BAITHI1
GO

CREATE TABLE CSCHANNUOI
(
	MACS VARCHAR(5) CONSTRAINT PK_CSCHANNUOI PRIMARY KEY NOT NULL,
	TENCS NVARCHAR(50),
	LOAICS VARCHAR(50),
	NGDAIDIEN VARCHAR(50),
	NGTL SMALLDATETIME,
	DTHOAI VARCHAR(10),
)

CREATE TABLE GIONGVN
(
	MAGIONG VARCHAR(4) CONSTRAINT PK_GIONGVN PRIMARY KEY NOT NULL,
	TENGIONG VARCHAR(50),
	LOAIVN VARCHAR(20)
)

CREATE TABLE DIEUKIENCN
(
	MADK VARCHAR(5) CONSTRAINT PK_DIEUKIEN PRIMARY KEY NOT NULL,
	MACS VARCHAR(5) 
	CONSTRAINT FK_MACS_DIEUKIEN FOREIGN KEY(MACS) REFERENCES CSCHANNUOI(MACS),
	QUYMO INT,
	KCXLCT INT,
	KCKDC INT
)

CREATE TABLE GPCN
(
	MAGP VARCHAR(5) CONSTRAINT PK_GPCN PRIMARY KEY NOT NULL,
	MACS VARCHAR(5),
	NGCAP SMALLDATETIME,
	SOGP VARCHAR(100),
	SOGIONG INT,
	CONSTRAINT FK_MACS_GPCN FOREIGN KEY(MACS) REFERENCES CSCHANNUOI(MACS), 
)

CREATE TABLE CTGP
(
	MAGP VARCHAR(5) NOT NULL,
	MAGIONG VARCHAR(4) NOT NULL,
	SL INT,
	CONSTRAINT PK_CTGP PRIMARY KEY(MAGP, MAGIONG),
	CONSTRAINT FK_MAGP_CTGP FOREIGN KEY(MAGP) REFERENCES GPCN(MAGP),
	CONSTRAINT FK_MAGIONG_CTGP FOREIGN KEY(MAGIONG) REFERENCES GIONGVN(MAGIONG)
)

CREATE TABLE DOTCN
(
	MADOTCN VARCHAR(4) CONSTRAINT PK_DOTCN PRIMARY KEY NOT NULL,
	MACS VARCHAR(5),
	MAGIONG VARCHAR(4),
	SLVN INT,
	NGBD SMALLDATETIME,
	PHGTHUC VARCHAR(50),
	NGXUATDK SMALLDATETIME
	CONSTRAINT FK_MACS_DOTCN FOREIGN KEY(MACS) REFERENCES CSCHANNUOI(MACS),
	CONSTRAINT FK_MAGIONG_DOTCN FOREIGN KEY(MAGIONG) REFERENCES GIONGVN(MAGIONG)
)

--2. Nhập dữ liệu cho 4 bảng CSCHANNUOI, GIONGVN, DIEUKIENCN và GPCN như đề bài
SET DATEFORMAT DMY

INSERT INTO CSCHANNUOI(MACS, TENCS, LOAICS, NGDAIDIEN, NGTL, DTHOAI) VALUES
('CS001','Hoang Mai','Nong ho','Nguyen Thanh Son','19/10/2019','0971507394'),
('CS002','Cong ty TNHH Phung Dầu Sơn','Trang trai quy mo vua','Pham The Hung','20/10/2009','0364266792'),
('CS003','Green Farm','Trang trai quy mo nho','Ho Trung Dai','15/09/2018','0356266782')

INSERT INTO GIONGVN(MAGIONG, TENGIONG, LOAIVN) VALUES
('G001','Bo vang Viet Nam','Bo'),
('G002','Bo Bay Nui','Bo'),
('G003','De nui Ninh Binh','De')

INSERT INTO DIEUKIENCN(MADK, MACS, QUYMO, KCXLCT, KCKDC) VALUES
('DK001','CS001','10','250','300'),
('DK002','CS001','10','200','350'),
('DK003','CS003','30','350','400')

INSERT INTO GPCN(MAGP, MACS, NGCAP, SOGP, SOGIONG) VALUES
('GP001','CS001','10/10/2020','42/001/2020/DKCN','1'),
('GP002','CS001','08/09/2020','43/001/2020/DKCN','2'),
('GP003','CS002','04/06/2010','2/002/2010/DKCN','4')

INSERT INTO CTGP(MAGP, MAGIONG, SL) VALUES
('GP001','G001','10'),
('GP002','G002','10'),
('GP003','G003','10')

INSERT INTO DOTCN(MADOTCN, MACS, MAGIONG, SLVN, NGBD, PHGTHUC, NGXUATDK) VALUES
('D001','CS001','G001','5','15/06/2021','Tha tu do','15/05/2023'),
('D002','CS001','G002','5','15/07/2021','Tha tu do','10/05/2023'),
('D003','CS003','G001','25','20/09/2021','Tha tu do','10/03/2022')

--3. Hiện thực ràng buộc toàn vẹn sau: số lượng vật nuôi từ 100 trở lên không được 
--phép chăn nuôi theo phương thức “thả tự do”
ALTER TABLE DOTCN
ADD CONSTRAINT CHECK_SLVN_PHGTHUC CHECK (
	NOT (SLVN >= 100 AND PHGTHUC = 'Tha tu do')
)


--4. Hiện thực ràng buộc toàn vẹn sau: các giống của loại vật nuôi "Bo" có thời gian 
--xuất dự kiến cách ngày bắt đầu nuôi ít nhất 12 tháng (1.5đ). 
GO
CREATE TRIGGER CHECK_BO_12_THANG ON DOTCN
AFTER INSERT
AS
BEGIN
	IF EXISTS(
		SELECT *
		FROM inserted I, GIONGVN G
		WHERE I.MAGIONG = G.MAGIONG
		AND G.LOAIVN = 'Bo'
		AND DATEDIFF(MONTH, I.NGBD, I.NGXUATDK) < 12
	)
	BEGIN
		RAISERROR('LOI: BO VA TREN 12 THANG', 16, 1)
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT 'THEM THANH CONG!'
	END
END
GO

--5. Tìm các giống vật nuôi (MAGIONG, TENGIONG) thuộc loại “Bo” được chăn nuôi theo phương thức “thả tự do” dự kiến xuất trong tháng 12/2024 (1đ). 
SELECT G.MAGIONG, TENGIONG
FROM GIONGVN G, DOTCN D
WHERE G.MAGIONG = D.MAGIONG AND G.LOAIVN = 'Bo' AND D.PHGTHUC = 'Tha tu do'
AND MONTH(D.NGXUATDK) = 12 AND YEAR(D.NGXUATDK) = 2024

--6. Tìm cơ sở chăn nuôi (MACS, TENCS) chưa có giấy phép chăn nuôi nào được cấp cho giống vật nuôi thuộc loại “De” nhưng đã từng có đợt chăn nuôi các giống vật nuôi loại này trong năm 2024 (1đ). 
SELECT C.MACS, C.TENCS
FROM CSCHANNUOI C
JOIN DOTCN D ON D.MACS = C.MACS
JOIN GIONGVN G ON G.MAGIONG = D.MAGIONG
WHERE LOAIVN = 'De' AND YEAR(NGBD) =2024
	EXCEPT
SELECT C.MACS, C.TENCS
FROM CSCHANNUOI C, GPCN GP, GIONGVN G, CTGP
WHERE C.MACS = GP.MACS AND CTGP.MAGIONG = G.MAGIONG AND CTGP.MAGP = GP.MAGP
AND LOAIVN = 'De'

--7. Tính thời gian nuôi thực tế trung bình (theo đơn vị tháng) của từng loại vật nuôi theo từng hình thức chăn nuôi (1đ). 
-- CACH 1
SELECT G.LOAIVN, D.PHGTHUC, AVG(12*(YEAR(NGXUATDK) - YEAR(NGBD)) + (MONTH(NGXUATDK) - MONTH(NGBD))) THOIGIANNUOITRUNGBINH
FROM DOTCN D, GIONGVN G
WHERE D.MAGIONG = G.MAGIONG
GROUP BY G.LOAIVN, D.PHGTHUC
-- CACH 2
SELECT G.LOAIVN, D.PHGTHUC, AVG(DATEDIFF(MONTH, NGBD, NGXUATDK)) THOIGIANNUOITRUNGBINH
FROM DOTCN D, GIONGVN G
WHERE D.MAGIONG = G.MAGIONG
GROUP BY G.LOAIVN, D.PHGTHUC


--8. Với từng loại vật nuôi tìm giống vật nuôi(MAGIONG) từng được cấp phép với tổng số lượng nhiều nhất năm 2024 (1đ). 
SELECT TOP 1 WITH TIES G.LOAIVN, G.MAGIONG, SUM(D.SLVN) SLVN
FROM GIONGVN G, DOTCN D
WHERE G.MAGIONG = D.MAGIONG AND YEAR(D.NGBD) = 2024
GROUP BY G.LOAIVN, G.MAGIONG
ORDER BY SUM(D.SLVN) DESC

--9. Tìm cơ sở chăn nuôi (MACS, TENCS) đã được cấp phép chăn nuôi tất cả các giống của loại vật nuôi “Bo” với số lượng mỗi giống đều từ 20 trở lên (1đ). 
SELECT C.MACS, C.TENCS
FROM CSCHANNUOI C
WHERE NOT EXISTS(
	SELECT *
	FROM GIONGVN G
	WHERE G.LOAIVN = 'Bo' 
	AND NOT EXISTS (
		SELECT *
		FROM GPCN G1, CTGP CT
		WHERE C.MACS = G1.MACS AND CT.MAGP = G1.MAGP AND CT.MAGIONG = G.MAGIONG
		AND SL >= 20
	)
)

------------------------------------------------------------De2-----------------------------------------------------------------------------------------
--1.	Tạo database tên BAITHI gồm có 6 table CSCHANNUOI, GIONGVN, DIEUKIENCN, GPCN, CTGP, DOTCN. Tạo khóa chính, khóa ngoại cho các table đó (1.5đ). 

/*
USE master
GO
DROP DATABASE BAITHI2
*/
USE master
CREATE DATABASE BAITHI2
GO
USE BAITHI2

CREATE TABLE CSCHANNUOI(
	MACS VARCHAR(5) CONSTRAINT PK_CSCHANNUOI PRIMARY KEY NOT NULL,
	TENCS VARCHAR(20),
	LOAICS VARCHAR(50),
	NGDAIDIEN VARCHAR(50),
	NGTL SMALLDATETIME,
	DTHOAI VARCHAR(10)
)

CREATE TABLE GIONGVN(
	MAGIONG VARCHAR(4) CONSTRAINT PK_GIONGVN PRIMARY KEY NOT NULL,
	TENGIONG VARCHAR(20),
	LOAIVN VARCHAR(20)
)

CREATE TABLE DIEUKIENCN(
	MADK VARCHAR(5) CONSTRAINT PK_DIEUKIENCN PRIMARY KEY NOT NULL,
	MACS VARCHAR(5),
	QUYMO INT,
	KCXLCT  INT,
	KCHTNSH INT,
	CONSTRAINT FK_MACS_DIEUKIENCN FOREIGN KEY(MACS) REFERENCES CSCHANNUOI(MACS)
)

CREATE TABLE GPCN(
	MAGP VARCHAR(5) CONSTRAINT PK_GPCN PRIMARY KEY NOT NULL,
	MACS VARCHAR(5),
	NGCAP SMALLDATETIME,
	SOGP VARCHAR(50),
	SOGIONG INT,
	CONSTRAINT FK_MACS_GPCN FOREIGN KEY(MACS) REFERENCES CSCHANNUOI(MACS)
)

CREATE TABLE CTGP(
	MAGP VARCHAR(5) NOT NULL,
	MAGIONG VARCHAR(4) NOT NULL,
	SL INT,
	CONSTRAINT PK_MAGP_MAGIONG_CTGP PRIMARY KEY(MAGP, MAGIONG),
	CONSTRAINT FK_MAGP_CTGP FOREIGN KEY(MAGP) REFERENCES GPCN(MAGP),
	CONSTRAINT FK_MAGIONG_CTGP FOREIGN KEY(MAGIONG) REFERENCES GIONGVN(MAGIONG)
)

CREATE TABLE DOTCN(
	MADOTCN VARCHAR(4) CONSTRAINT PK_DOTCN PRIMARY KEY NOT NULL,
	MACS VARCHAR(5),
	MAGIONG VARCHAR(4),
	SLVN INT,
	NGBD SMALLDATETIME,
	PHGTHUC VARCHAR(20),
	NGXUATDK SMALLDATETIME,
	CONSTRAINT FK_MACS_DOTCN FOREIGN KEY(MACS) REFERENCES CSCHANNUOI(MACS),
	CONSTRAINT FK_MAGIONG_DOTCN FOREIGN KEY(MAGIONG) REFERENCES GIONGVN(MAGIONG)
)
--2.	Nhập dữ liệu cho 4 bảng CSCHANNUOI, GIONGVN, DIEUKIENCN và GPCN như đề bài (1đ). 
SET DATEFORMAT DMY

INSERT INTO CSCHANNUOI(MACS , TENCS , LOAICS , NGDAIDIEN , NGTL , DTHOAI ) VALUES
('CS001 ','Tam Viet ','Nong ho ','Bui Phu Lam ','19/10/2018 ','0971507142 '),
('CS002 ','Cam My ','Trang trai quy mo vua ','Le Thi Hong Tuyet ','20/10/2008 ','0364266762 '),
('CS003 ','Me Non ','Trang trai quy mo nho ','Ngo Van Thanh ','15/09/2017 ','0356266967 ')

INSERT INTO GIONGVN(MAGIONG , TENGIONG , LOAIVN ) VALUES
('G001 ','Heo ba xuyen ','Heo '),
('G002 ','Heo moi ','Heo '),
('G003 ','Bo lai Sind ','Bo ')

INSERT INTO GPCN(MAGP, MACS, NGCAP, SOGP, SOGIONG) VALUES
('GP001 ','CS001 ','10/10/2019 ','42/001/2019/DKCN ','1 '),
('GP002 ','CS001 ','08/09/2019 ','43/001/2019/DKCN ','2 '),
('GP003 ','CS002 ','04/06/2009 ','2/002/2009/DKCN ','4 ')

INSERT INTO CTGP(MAGP , MAGIONG , SL ) VALUES
('GP001 ','G001 ','10 '),
('GP002 ','G002 ','10 '),
('GP002 ','G003 ','10 ')

INSERT INTO DOTCN(MADOTCN , MACS , MAGIONG , SLVN , NGBD , PHGTHUC , NGXUATDK ) VALUES
('D001 ','CS001 ','G001 ','5 ','15/06/2021 ','Nuoi cong nghiep ','15/09/2021 '),
('D002 ','CS001 ','G002 ','5 ','15/07/2021 ','Tha tu do ','10/01/2022 '),
('D003 ','CS003 ','G001 ','25 ','20/09/2021 ','Tha tu do ','10/08/2023 ')

--3.Hiện thực ràng buộc toàn vẹn sau: các giấy phép được cấp trước năm 2019 có số giống được cấp phép tối đa 5 giống một lần cấp (1đ). 
/*ALTER TABLE GPCN
ADD CONSTRAINT CHK_CAPPHEP CHECK(YEAR(NGCAP) < 2019 AND SOGIONG <= 5)
-- KHONG THE CONSTRAINT DUOC VI CHECK KHONG HO TRO HAM YEAR*/
GO
CREATE TRIGGER TRG_CAPPHEP ON GPCN
AFTER INSERT
AS
BEGIN
	IF EXISTS(
		SELECT *
		FROM inserted I
		WHERE YEAR(I.NGCAP) >= 2019 OR I.SOGIONG > 5
	)
	BEGIN
		RAISERROR('LOI: KHONG THOA NAM < 2019 VA SOGIONG')
		ROLLBACK TRAN
	END
	ELSE
	BEGIN
		PRINT 'THEM THANH CONG!' 
	END
END

--4.Hiện thực ràng buộc toàn vẹn sau: các giống vật nuôi loại "Heo" chỉ được cấp giấy phép chăn nuôi với số lượng tối đa là 100 vật nuôi (1.5đ). 
GO
CREATE TRIGGER TRG_CHECK_SOLUONG_HEO ON GIONGVN
AFTER INSERT
AS
BEGIN
	IF EXISTS(
		SELECT *
		FROM inserted I, CTGP C
		WHERE I.MAGIONG = C.MAGIONG AND LOAIVN = 'Heo' AND SL > 100
	)
	BEGIN
		RAISERROR('LOI: SO LUONG HEO IT HON 100', 16, 1)
		ROLLBACK TRAN
	END
	ELSE
	BEGIN
		PRINT 'THEM THANH CONG!'
	END
END

--5.Tìm các cơ sở chăn nuôi (MACS, TENCS) thuộc loại “nong ho” có quy mô trên 30 vật nuôi và có khoảng cách đến khu xử lý chất thải dưới 200 mét (1đ). 
SELECT C.MACS, C.TENCS
FROM CSCHANNUOI C, DIEUKIENCN D
WHERE C.MACS = D.MACS AND LOAICS = 'Nong ho' AND QUYMO > 30 AND KCXLCT < 200

--6.Tìm các giống vật nuôi (MAGIONG, TENGIONG) thuộc loại “Bo” đã từng được cấp phép chăn nuôi nhưng chưa được nuôi đợt nào năm 2024 (1đ).  
SELECT GV.MAGIONG, GV.TENGIONG
FROM GIONGVN GV, CTGP C
WHERE GV.MAGIONG = C.MAGIONG AND LOAIVN = 'Bo'
	EXCEPT
SELECT GV.MAGIONG, GV.TENGIONG
FROM GIONGVN GV, DOTCN D
WHERE GV.MAGIONG = D.MAGIONG AND LOAIVN = 'Bo' AND YEAR(NGBD) = 2024


--7.Tính thời gian nuôi thực tế dài nhất (theo đơn vị tháng) của từng loại vật nuôi theo từng hình thức chăn nuôi (1đ). 
SELECT G.LOAIVN, D.PHGTHUC, MAX(DATEDIFF(MONTH, D.NGBD, D.NGXUATDK)) AS MaxDuration
FROM DOTCN D
JOIN GIONGVN G ON D.MAGIONG = G.MAGIONG
GROUP BY G.LOAIVN, D.PHGTHUC;

--8.	Với từng loại vật nuôi tìm giống vật nuôi (MAGIONG) từng được chăn nuôi với tổng số lượng nuôi thực tế nhiều nhất năm 2024 (1đ). 
SELECT TOP 1 WITH TIES D.MAGIONG, LOAIVN, SUM(SLVN)
FROM DOTCN D, GIONGVN G
WHERE D.MAGIONG = G.MAGIONG AND YEAR(NGBD) = 2024
GROUP BY D.MAGIONG, LOAIVN
ORDER BY SUM(SLVN) DESC

--9.	Tìm cơ sở chăn nuôi (MACS, TENCS) đã từng chăn nuôi tất cả các giống của loại vật nuôi “Heo” với số lượng chăn nuôi thực tế từ 20 vật nuôi trở lên (1đ). 
SELECT C.MACS, C.TENCS
FROM CSCHANNUOI C
WHERE NOT EXISTS (
    SELECT *
    FROM GIONGVN G
    WHERE G.LOAIVN = 'Heo'
    AND NOT EXISTS (
        SELECT *
        FROM DOTCN D
        WHERE D.MACS = C.MACS 
          AND D.MAGIONG = G.MAGIONG
          AND D.SLVN >= 20
    )
)

